---
title: "Census data processing"
output: html_notebook
---

```{r}
library(stringr)
library(plyr)
```

```{r}
df = read.csv('../data/seedling_census_raw_data.csv',header=TRUE)
df_meta = read.csv('../Seedling_Metadata_05.27.2021.csv',header=TRUE)
```

```{r}
head(df_meta)
```

```{r}
head(df)
```

```{r}
df$Seedling_ID = str_replace_all(df$Seedling_ID,'-','_')
df = df[which(df$Data.to.delete!='yes'),]
df$Data.to.delete = NULL
df$Seedling_ID_2 = NULL
df$to.check.in.context = NULL
df$Changes.made.during.cleaning = NULL
df$New_Individual = NULL
df$Num_cotyledons_20191210_and_on[which(is.na(df$Num_cotyledons_20191210_and_on))] = 0
df[which(df$Num_Hojas=='coteledon'),'Num_Hojas'] = 2
df[which(df$Num_Hojas=='DEAD'),'Num_Hojas'] = 0
df[which(df$Num_Hojas=='N/A'),'Num_Hojas'] = 6 #This individual has 6 leaves several days later, so looks like a missed entry
df[which(df$Seedling_ID=='06187_1901_01'),'Num_Hojas'] = 2 #Has to have been 2 (leaflets were orginally counted as leaves, but switched to leaves until collected)
df[which(df$Seedling_ID=='06187_1901_03'),'Num_Hojas'] = 3 #Was 3 for the rest of the time, so must have been 3
df[which(df$Seedling_ID=='12249_1901_01'),'Num_Hojas'] = 2 #Average number for similarly sized simarouba
df[which(df$Seedling_ID=='12525_1901_01'),'Num_Hojas'] = 2 #Average number for similarly sized simarouba
#df$Num_Hojas = df$Num_Hojas + df$Num_cotyledons_20191210_and_on
df[which((df$Seedling_ID=='12855_0820_01')&(df$Date<20190713)),'Num_Hojas'] = 0 #Germinating seedling that had 0 value for leaves for the next few timepoints
df[which((df$Seedling_ID=='12855_1901_01')&(df$Date<20190729)),'Num_Hojas'] = 3 #Was 3 thereafter, so was likely 3
df[which((df$Seedling_ID=='13665_1901_01')&(df$Date<20190729)),'Num_Hojas'] = 3 #Checked photo
df[which((df$Seedling_ID=='13665_1901_02')&(df$Date<20190729)),'Num_Hojas'] = 2 #Checked photo
df[which((df$Seedling_ID=='13665_1901_03')&(df$Date<20190729)),'Num_Hojas'] = 1 #Average for similarly sized seedlings
df[which((df$Seedling_ID=='13665_1901_04')&(df$Date<20190729)),'Num_Hojas'] = 1 #Checked photo
df[which((df$Seedling_ID=='13665_1901_05')&(df$Date<20190729)),'Num_Hojas'] = 0 #Checked photo
df[which((df$Seedling_ID=='12855_0820_02')&(df$Date<20190715)),'Num_Hojas'] = 0 #Had 0 for several censuses after
df[which(df$Num_Hojas==''),'Num_Hojas'] = NA
df$Seedling_ID = str_replace_all(df$Seedling_ID,'6187','1687')
df[which(df$Arbol_Tag==6187),'Arbol_Tag'] = 1687
df[which((df$Seedling_ID=='01687_1901_02')&is.na(df$Num_Hojas)),'Num_Hojas'] = 2 #Likely first two leaves before being clipped
df[which((df$Seedling_ID=='01687_1901_02')&(df$Num_Hojas==0)),'Herb_.'] = 1 #Leaves clipped
df$Num_Hojas = as.numeric(as.character(df$Num_Hojas))
df$Num_Leaves = df$Num_Hojas+df$Num_cotyledons_20191210_and_on
df$Num_Hojas = NULL
df$Num_cotyledons_20191210_and_on = NULL
df$Height = df$Altura
df$Altura = NULL
df$AdultTag = df$Arbol_Tag
df$Arbol_Tag = NULL
df$Seedling_Species = mapvalues(df$Species_Code,from=c(407,803,820,1901),to=c('DG','HC','HT','SA'))
df$Species = NULL
df$Species_Code = NULL
df$Herbivory = df$Herb_.
df[which(df$Herbivory==''),'Herbivory'] = 0
df[which(df$Herbivory!=0),'Herbivory'] = 1
df$Herbivory = as.numeric(as.character(df$Herbivory))
df$Herb_. = NULL
df$Pathogen_Symptoms = df$Pathoj_.
df[which(df$Pathogen_Symptoms==''),'Pathogen_Symptoms'] = 0
df[which(df$Pathogen_Symptoms!=0),'Pathogen_Symptoms'] = 1
df$Pathogen_Symptoms = as.numeric(as.character(df$Pathogen_Symptoms))
df$Pathoj_. = NULL
#df$Concerns.with.point = NULL #Revisit each of these
```

```{r}
df[which(df$Concerns.with.point=="doesn't line up with any of the later points in terms of height"),'Concerns.with.point'] = '' #Germinating seedlings can sprout pretty quickly. Not an issue
df[which(df$Concerns.with.point=="height jumped up 4 cm in 10 days"),'Concerns.with.point'] = '' #Not unusual
df[which((df$Seedling_ID=='01401_0820_08')&(df$Date>20190917)),'Seedling_ID'] = '01401_0820_11'
df[which(df$Concerns.with.point=='said collected but then there was data afterwards'),'Concerns.with.point'] = ''
df[which((df$Seedling_ID=='02512_0820_14')&(df$Date>=20191106)),'Seedling_ID'] = '02512_0820_16'
df[which(df$Concerns.with.point=='only 1 entry'),'Concerns.with.point'] = ''#Actually many nore entries
df[which(df$Concerns.with.point=='only 1 entry '),'Concerns.with.point'] = ''#Must have died quickly
df[which(df$Concerns.with.point=='sudden jump in leaf number and height in 4 days; consistent for rest of entries for this point'),'Concerns.with.point'] = ''#Looks like it just finished germninating
df[which(df$Concerns.with.point=='height jumps 4 cm in 6 days'),'Concerns.with.point'] = ''#Finished germinating
df[which(df$Concerns.with.point=='height went from 10 to 15 (later returns to 10)'),'Height'] = 10#Looks like issue with data entry given overlapping issue with leaf count. Height should be 10
df[which(df$Concerns.with.point=='height went from 10 to 15 (later returns to 10)'),'Concerns.with.point'] = ''#Issue resolved in previous line
df[which(df$Concerns.with.point=='only one entry recorded and its 100% herbivory'),'Concerns.with.point'] = ''#New germination was eaten by an herbivore
df[which(df$Concerns.with.point=='height jumped 5 cm in 5 days'),'Concerns.with.point'] = ''#Finished germinating
df[which(df$Concerns.with.point=='height is 3 but 3 days later its 9 and stays that way'),'Concerns.with.point'] = ''#Finished germinating
df = df[which(!(df$Seedling_ID=='12855_0803_02')&!(df$Date>=20190815)),] #Additional data after the seedling died.
df[which(!(df$Concerns.with.point=='says "dead" on OG sheet that I didnt make but there is later data; deleted rest of "dead\' entries and moved into "deleted sheet"')),] #Additional data after the seedling died.
df[which(df$Concerns.with.point=='paper says 0407'),'Concerns.with.point'] = '' #Seems to have been sorted out
df[which(df$Concerns.with.point=='height 2.5 cm less than day before'),'Concerns.with.point'] = '' #Noise in measurement
df[which(df$Concerns.with.point=='no data except 0 hojas'),'Height'] = 0 #Looks like it was just starting to germinate
df[which(df$Concerns.with.point=='no data except 0 hojas'),'Concerns.with.point'] = '' #Looks like it was just starting to germinate
df[which(df$Concerns.with.point=='only entry '),'Concerns.with.point'] = '' #Looks like it was collected or died quickly
df[which(df$Concerns.with.point=='Leaf # is 0 (even though before and after its 2/3)'),'Concerns.with.point'] = '' #Plant must have recovered, but should check photos
df[which((df$Seedling_ID=='42320_1901_01')&(df$Herbivory==0)),'Num_Leaves'] = 2#Leaf number 1 once herbivory shows up, so should be 2 before
df[which(df$Concerns.with.point=='height significantly higher than before/after'),'Concerns.with.point'] = '' #Resolved
df[which(df$Concerns.with.point=='there were ~10 entries prior that listed the seedling as dead'),'Concerns.with.point'] = ''#No relevant growth data from deleted entries, so keeping the current ID
df[which(df$Concerns.with.point=='says "dead" on OG sheet that I didnt make but there is later data; deleted rest of "dead\' entries and moved into "deleted sheet"'),'Concerns.with.point'] = ''#No relevant growth data from deleted entries, so keeping the current ID
unique(df$Concerns.with.point)
```
```{r}
#Addressing notes
df$Cause_of_death = rep(c(''),times=nrow(df))
df[which(df$Seedling_ID%in%df[which(df$Notes=='Recolecta'),'Seedling_ID']),'Cause_of_death'] = 'Collected' #CHECK THESE
df[which(df$Notes=='Recolecta'),'Notes'] = ''
df[which(df$Seedling_ID%in%df[which(df$Notes=='Collected Aug 28'),'Seedling_ID']),'Cause_of_death'] = 'Collected'#CHECK THESE
df[which(df$Notes=='Collected Aug 28'),'Notes'] = ''
df[which(df$Seedling_ID%in%df[which(df$Notes=='20191118: recolecta'),'Seedling_ID']),'Cause_of_death'] = 'Collected'#CHECK THESE
df[which(df$Notes=='20191118: recolecta'),'Notes'] = ''
df[which(grepl('en 1 hoja',df$Notes)),'Notes'] = ''
df[which(grepl('en 2 hoja',df$Notes)),'Notes'] = ''
df[which(grepl('en 3 hoja',df$Notes)),'Notes'] = ''
df[which(df$Seedling_ID=='01401_0820_08'),'Cause_of_death'] = 'Pathogen'
df[which(df$Seedling_ID=='01401_0820_08'),'Notes'] = ''


df[which(df$Notes=='1 hoja'),'Notes'] = ''
df[which(df$Notes=='en 1 hoja'),'Notes'] = ''
df[which(df$Notes=='20200206: nueva jerminacion'),'Notes'] = ''
df[which(grepl('nueva jerminacion',df$Notes)),'Notes'] = ''
df[which(grepl('nueva',df$Notes)),'Notes'] = ''
df[which(grepl('2 hojas',df$Notes)),'Notes'] = ''
df = df[!(df$Notes=='no data 20191004 or 20191010'),]
df[which(df$Notes=='saludoble'),'Notes'] = ''
df[which(df$Notes=='20190724: no data'),'Notes'] = ''#Looks like data was eventually found
df[which(df$Notes=='leaf number too high so was removed'),'Notes'] = ''#These issues were fixed (Simaroubas for which leaflet # was counted instead of leafs)
df[which(df$Notes=='leaf number seemed reasonable'),'Notes'] = ''#These issues were fixed (Simaroubas for which leaflet # was counted instead of leafs)
df[which(df$Seedling_ID=='12525_0407_02'),'Cause_of_death'] = 'Pathogen'
df[which(df$Notes=='Dead (recolecta Aug 5 or earlier)'),'Notes'] = '' #Added cause of death
df[which(df$Seedling_ID=='13665_1901_04'),'Cause_of_death'] = 'Herbivory then Pathogen'
df[which(df$Notes=='muerto por patejeno'),'Notes'] = '' #Added cause of death
df[which(df$Seedling_ID=='42320_1901_02'),'Cause_of_death'] = 'Herbivory then Pathogen'
df[which(df$Notes=='Recolectada; muerta por patejeno, but earlier says by herbivory'),'Notes'] = ''#Added cause of death
df[which(df$Notes=='50% new? so now 25% of original plant exists?'),'Notes'] = ''#Herbivory is a boolean now, so this is irrelevant
df[which(df$Seedling_ID=='58779_0820_03'),'Cause_of_death'] = 'Herbivory then Pathogen'
df[which(df$Notes=='Muerta por pathoenjo '),'Notes'] = '' #Added cause of death
df[which(df$Notes=="Dan wrote plant #3, but it's been #2"),'Notes'] = ''#Resolved
df[which(df$Notes=="has an 'x' on data sheet and some illegible"),'Notes'] = ''#Resolved
##########Note: remove duplicate entries#############


unique(df$Notes)
```
```{r}
switched_IDs = data.frame('Seedling_ID_original'=c('01401_0820_08','02512_0820_14'),
           'Seedling_ID_new'=c('01401_0820_11','02512_0820_16'),
           'Date_collected_or_died_original'=c(20190916,20191015),
           'Date_started_new'=c(20190917,20191106))
```




```{r}
write.csv(df,'../data/Seedling_census_data_curated_11_21_21.csv',row.names=FALSE)
```
Add adult tag, adult species, seedling species, seedling ID, etc.
```{r}

df$AdultTag <- lapply(df$Seedling_ID, function(x) as.numeric(strsplit(x,'_')[[1]][1]))
df$Exclosure_Code <- lapply(df$Seedling_ID, function(x) as.numeric(strsplit(x,'_')[[1]][2]))
df$Seedling_Rep <- lapply(df$Seedling_ID, function(x) as.numeric(strsplit(x,'_')[[1]][3]))

df$AdultTag = df$Seedling_ID
```






